-- 1. Create Users Table
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) NOT NULL CHECK (role IN ('restaurant', 'ngo')),
    restaurant_name VARCHAR2(100),
    contact_phone VARCHAR2(15),
    contact_email VARCHAR2(150),
    is_active NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);
/

-- 2. Create Food Donations Table
CREATE TABLE food_donations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    food_type VARCHAR2(100) NOT NULL,
    quantity NUMBER NOT NULL,
    expiry_time TIMESTAMP NOT NULL,
    status VARCHAR2(20) DEFAULT 'Available' CHECK (status IN ('Available', 'Claimed', 'Expired')),
    pickup_notes VARCHAR2(4000),
    pickup_location VARCHAR2(255),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_fd_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
/

-- 3. Create Donation Claims Table
CREATE TABLE donation_claims (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donation_id NUMBER NOT NULL UNIQUE,
    ngo_user_id NUMBER NOT NULL,
    claimed_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_dc_donation FOREIGN KEY (donation_id) REFERENCES food_donations(id) ON DELETE CASCADE,
    CONSTRAINT fk_dc_ngo FOREIGN KEY (ngo_user_id) REFERENCES users(id) ON DELETE CASCADE
);
/

-- 4. Create Audit Log Table
CREATE TABLE audit_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR2(50) NOT NULL,
    table_name VARCHAR2(50) NOT NULL,
    record_id NUMBER NOT NULL,
    old_value VARCHAR2(255),
    new_value VARCHAR2(255),
    performed_by NUMBER,
    action_time TIMESTAMP DEFAULT SYSTIMESTAMP
);
/